


GET http://localhost:6000/api/v1/message HTTP/1.1
###

GET http://localhost:6000/api/v1/message/5782c898-c645-4b7e-847f-315772f19b91 HTTP/1.1
###

GET http://localhost:6000/api/v1/message/2 HTTP/1.1
###

POST http://localhost:6000/api/v1/message HTTP/1.1
content-type: application/json

{
  "user": "asdfasdf janne2",
  "text": "haloj jag var i Sverige, bra väder"
}
###
//Faulty post
POST http://localhost:6000/api/v1/message HTTP/1.1
content-type: application/json

{
  "user2": "asdfasdf janne2",
  "text3": "haloj jag var i Sverige, bra väder"
}
###

PUT http://localhost:6000/api/v1/message/32e2bf59-ae96-4967-ab05-c7d7f898dbf9 HTTP/1.1
content-type: application/json

{
  "user": "Jag har blivit utbytt2",
  "text": "haloj jag var i Sverige, bra väder",
  "hej": "n"
}

###
DELETE http://localhost:6000/api/v1/message/931c8e54-5884-4dfe-8d5c-7df46f1720d3 HTTP/1.1
###













